remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: "U.S. Power Grid Failures"
description: "Climate, Infrastructure, and Predictive Modeling of Mass-Impact Outages (2000–2016)"